---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: antScheduler
  annotations:
    github.com/project-slug: mcalus3/antScheduler
spec:
  type: other
  lifecycle: unknown
  owner: guest
