# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 601)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlWidget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlWidget.sizePolicy().hasHeightForWidth())
        self.controlWidget.setSizePolicy(sizePolicy)
        self.controlWidget.setMinimumSize(QtCore.QSize(140, 0))
        self.controlWidget.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.controlWidget.setFont(font)
        self.controlWidget.setObjectName("controlWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlWidget)
        self.verticalLayout.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StartButton = QtWidgets.QPushButton(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout.addWidget(self.StartButton, 0, QtCore.Qt.AlignHCenter)
        self.StopButton = QtWidgets.QPushButton(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopButton.sizePolicy().hasHeightForWidth())
        self.StopButton.setSizePolicy(sizePolicy)
        self.StopButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout.addWidget(self.StopButton, 0, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.controlWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.OperationList = QtWidgets.QPlainTextEdit(self.controlWidget)
        self.OperationList.setObjectName("OperationList")
        self.verticalLayout.addWidget(self.OperationList)
        self.CreateButton = QtWidgets.QPushButton(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateButton.sizePolicy().hasHeightForWidth())
        self.CreateButton.setSizePolicy(sizePolicy)
        self.CreateButton.setMinimumSize(QtCore.QSize(100, 40))
        self.CreateButton.setObjectName("CreateButton")
        self.verticalLayout.addWidget(self.CreateButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.controlWidget)
        self.viewsTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewsTabWidget.sizePolicy().hasHeightForWidth())
        self.viewsTabWidget.setSizePolicy(sizePolicy)
        self.viewsTabWidget.setMinimumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.viewsTabWidget.setFont(font)
        self.viewsTabWidget.setObjectName("viewsTabWidget")
        self.Process = QtWidgets.QWidget()
        self.Process.setObjectName("Process")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Process)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.processView = QtWidgets.QGraphicsView(self.Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processView.sizePolicy().hasHeightForWidth())
        self.processView.setSizePolicy(sizePolicy)
        self.processView.setObjectName("processView")
        self.horizontalLayout_2.addWidget(self.processView)
        self.viewsTabWidget.addTab(self.Process, "")
        self.Pheromone = QtWidgets.QWidget()
        self.Pheromone.setObjectName("Pheromone")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Pheromone)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pheromoneView = QtWidgets.QGraphicsView(self.Pheromone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pheromoneView.sizePolicy().hasHeightForWidth())
        self.pheromoneView.setSizePolicy(sizePolicy)
        self.pheromoneView.setObjectName("pheromoneView")
        self.horizontalLayout_6.addWidget(self.pheromoneView)
        self.viewsTabWidget.addTab(self.Pheromone, "")
        self.Result = QtWidgets.QWidget()
        self.Result.setObjectName("Result")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Result)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.resultView = QtWidgets.QGraphicsView(self.Result)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultView.sizePolicy().hasHeightForWidth())
        self.resultView.setSizePolicy(sizePolicy)
        self.resultView.setObjectName("resultView")
        self.horizontalLayout_5.addWidget(self.resultView)
        self.viewsTabWidget.addTab(self.Result, "")
        self.Schedule = QtWidgets.QWidget()
        self.Schedule.setObjectName("Schedule")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Schedule)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scheduleView = QtWidgets.QGraphicsView(self.Schedule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scheduleView.sizePolicy().hasHeightForWidth())
        self.scheduleView.setSizePolicy(sizePolicy)
        self.scheduleView.setObjectName("scheduleView")
        self.horizontalLayout_4.addWidget(self.scheduleView)
        self.viewsTabWidget.addTab(self.Schedule, "")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.History)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.historyView = QtWidgets.QGraphicsView(self.History)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyView.sizePolicy().hasHeightForWidth())
        self.historyView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.historyView.setFont(font)
        self.historyView.setObjectName("historyView")
        self.horizontalLayout_3.addWidget(self.historyView)
        self.viewsTabWidget.addTab(self.History, "")
        self.horizontalLayout.addWidget(self.viewsTabWidget)
        self.configScrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configScrollArea.sizePolicy().hasHeightForWidth())
        self.configScrollArea.setSizePolicy(sizePolicy)
        self.configScrollArea.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.configScrollArea.setFont(font)
        self.configScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.configScrollArea.setLineWidth(1)
        self.configScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.configScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.configScrollArea.setWidgetResizable(True)
        self.configScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.configScrollArea.setObjectName("configScrollArea")
        self.configScrollAreaWidgetContents = QtWidgets.QWidget()
        self.configScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 160, 528))
        self.configScrollAreaWidgetContents.setObjectName("configScrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.configScrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.algorithmComboBox = QtWidgets.QComboBox(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algorithmComboBox.sizePolicy().hasHeightForWidth())
        self.algorithmComboBox.setSizePolicy(sizePolicy)
        self.algorithmComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.algorithmComboBox.setFont(font)
        self.algorithmComboBox.setObjectName("algorithmComboBox")
        self.algorithmComboBox.addItem("")
        self.algorithmComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.algorithmComboBox, 0, QtCore.Qt.AlignTop)
        self.label_3 = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignBottom)
        self.iterationsLineEdit = QtWidgets.QLineEdit(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iterationsLineEdit.sizePolicy().hasHeightForWidth())
        self.iterationsLineEdit.setSizePolicy(sizePolicy)
        self.iterationsLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.iterationsLineEdit.setFont(font)
        self.iterationsLineEdit.setObjectName("iterationsLineEdit")
        self.verticalLayout_2.addWidget(self.iterationsLineEdit)
        self.label_4 = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignBottom)
        self.antPopulationLineEdit = QtWidgets.QLineEdit(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antPopulationLineEdit.sizePolicy().hasHeightForWidth())
        self.antPopulationLineEdit.setSizePolicy(sizePolicy)
        self.antPopulationLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.antPopulationLineEdit.setFont(font)
        self.antPopulationLineEdit.setObjectName("antPopulationLineEdit")
        self.verticalLayout_2.addWidget(self.antPopulationLineEdit)
        self.label_5 = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignBottom)
        self.evaporationRateLineEdit = QtWidgets.QLineEdit(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evaporationRateLineEdit.sizePolicy().hasHeightForWidth())
        self.evaporationRateLineEdit.setSizePolicy(sizePolicy)
        self.evaporationRateLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.evaporationRateLineEdit.setFont(font)
        self.evaporationRateLineEdit.setObjectName("evaporationRateLineEdit")
        self.verticalLayout_2.addWidget(self.evaporationRateLineEdit)
        self.label_6 = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6, 0, QtCore.Qt.AlignBottom)
        self.pheromonePotencyLineEdit = QtWidgets.QLineEdit(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pheromonePotencyLineEdit.sizePolicy().hasHeightForWidth())
        self.pheromonePotencyLineEdit.setSizePolicy(sizePolicy)
        self.pheromonePotencyLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pheromonePotencyLineEdit.setFont(font)
        self.pheromonePotencyLineEdit.setObjectName("pheromonePotencyLineEdit")
        self.verticalLayout_2.addWidget(self.pheromonePotencyLineEdit)
        self.label_8 = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignBottom)
        self.initPheromoneLineEdit = QtWidgets.QLineEdit(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initPheromoneLineEdit.sizePolicy().hasHeightForWidth())
        self.initPheromoneLineEdit.setSizePolicy(sizePolicy)
        self.initPheromoneLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.initPheromoneLineEdit.setFont(font)
        self.initPheromoneLineEdit.setObjectName("initPheromoneLineEdit")
        self.verticalLayout_2.addWidget(self.initPheromoneLineEdit)
        self.label_9 = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignBottom)
        self.antsPromotedLineEdit = QtWidgets.QLineEdit(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antsPromotedLineEdit.sizePolicy().hasHeightForWidth())
        self.antsPromotedLineEdit.setSizePolicy(sizePolicy)
        self.antsPromotedLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.antsPromotedLineEdit.setFont(font)
        self.antsPromotedLineEdit.setObjectName("antsPromotedLineEdit")
        self.verticalLayout_2.addWidget(self.antsPromotedLineEdit, 0, QtCore.Qt.AlignTop)
        self.label_7 = QtWidgets.QLabel(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7, 0, QtCore.Qt.AlignBottom)
        self.pheromoneDistributionLineEdit = QtWidgets.QLineEdit(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pheromoneDistributionLineEdit.sizePolicy().hasHeightForWidth())
        self.pheromoneDistributionLineEdit.setSizePolicy(sizePolicy)
        self.pheromoneDistributionLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pheromoneDistributionLineEdit.setFont(font)
        self.pheromoneDistributionLineEdit.setObjectName("pheromoneDistributionLineEdit")
        self.verticalLayout_2.addWidget(self.pheromoneDistributionLineEdit, 0, QtCore.Qt.AlignTop)
        self.configScrollArea.setWidget(self.configScrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.configScrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1099, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.viewsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AntScheduler"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.label_10.setText(_translate("MainWindow", "Operation list"))
        self.CreateButton.setText(_translate("MainWindow", "Create Graph"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Process), _translate("MainWindow", "Process"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Pheromone), _translate("MainWindow", "Pheromone"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Result), _translate("MainWindow", "Result"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Schedule), _translate("MainWindow", "Schedule"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.History), _translate("MainWindow", "History"))
        self.label.setText(_translate("MainWindow", "Algorithm type"))
        self.algorithmComboBox.setItemText(0, _translate("MainWindow", "Ant System"))
        self.algorithmComboBox.setItemText(1, _translate("MainWindow", "Max-Min"))
        self.label_3.setText(_translate("MainWindow", "Iterations"))
        self.label_4.setText(_translate("MainWindow", "Ant population"))
        self.label_5.setText(_translate("MainWindow", "Evaporation rate"))
        self.label_6.setText(_translate("MainWindow", "Pheromone potency"))
        self.label_8.setText(_translate("MainWindow", "init pheromone value"))
        self.label_9.setText(_translate("MainWindow", "Ants promoted "))
        self.label_7.setText(_translate("MainWindow", "Pheromone distribution"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

