# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 400)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlWidget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlWidget.sizePolicy().hasHeightForWidth())
        self.controlWidget.setSizePolicy(sizePolicy)
        self.controlWidget.setMinimumSize(QtCore.QSize(140, 0))
        self.controlWidget.setMaximumSize(QtCore.QSize(140, 16777215))
        self.controlWidget.setObjectName("controlWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlWidget)
        self.verticalLayout.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RunButton = QtWidgets.QPushButton(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunButton.sizePolicy().hasHeightForWidth())
        self.RunButton.setSizePolicy(sizePolicy)
        self.RunButton.setMinimumSize(QtCore.QSize(100, 40))
        self.RunButton.setObjectName("RunButton")
        self.verticalLayout.addWidget(self.RunButton, 0, QtCore.Qt.AlignHCenter)
        self.StopButton = QtWidgets.QPushButton(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopButton.sizePolicy().hasHeightForWidth())
        self.StopButton.setSizePolicy(sizePolicy)
        self.StopButton.setMinimumSize(QtCore.QSize(100, 40))
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout.addWidget(self.StopButton, 0, QtCore.Qt.AlignHCenter)
        self.consoleTabWidget = QtWidgets.QTabWidget(self.controlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleTabWidget.sizePolicy().hasHeightForWidth())
        self.consoleTabWidget.setSizePolicy(sizePolicy)
        self.consoleTabWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.consoleTabWidget.setObjectName("consoleTabWidget")
        self.logWidget = QtWidgets.QWidget()
        self.logWidget.setObjectName("logWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.logWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logTextBrowser = QtWidgets.QTextBrowser(self.logWidget)
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.verticalLayout_3.addWidget(self.logTextBrowser)
        self.consoleTabWidget.addTab(self.logWidget, "")
        self.inputProcessWidget = QtWidgets.QWidget()
        self.inputProcessWidget.setObjectName("inputProcessWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.inputProcessWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.processTextEdit = QtWidgets.QTextEdit(self.inputProcessWidget)
        self.processTextEdit.setObjectName("processTextEdit")
        self.verticalLayout_4.addWidget(self.processTextEdit)
        self.consoleTabWidget.addTab(self.inputProcessWidget, "")
        self.verticalLayout.addWidget(self.consoleTabWidget)
        self.horizontalLayout.addWidget(self.controlWidget)
        self.viewsTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewsTabWidget.sizePolicy().hasHeightForWidth())
        self.viewsTabWidget.setSizePolicy(sizePolicy)
        self.viewsTabWidget.setMinimumSize(QtCore.QSize(500, 300))
        self.viewsTabWidget.setObjectName("viewsTabWidget")
        self.Process = QtWidgets.QWidget()
        self.Process.setObjectName("Process")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Process)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.processView = QtWidgets.QGraphicsView(self.Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processView.sizePolicy().hasHeightForWidth())
        self.processView.setSizePolicy(sizePolicy)
        self.processView.setObjectName("processView")
        self.horizontalLayout_2.addWidget(self.processView)
        self.viewsTabWidget.addTab(self.Process, "")
        self.Pheromone = QtWidgets.QWidget()
        self.Pheromone.setObjectName("Pheromone")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Pheromone)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pheromoneView = QtWidgets.QGraphicsView(self.Pheromone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pheromoneView.sizePolicy().hasHeightForWidth())
        self.pheromoneView.setSizePolicy(sizePolicy)
        self.pheromoneView.setObjectName("pheromoneView")
        self.horizontalLayout_6.addWidget(self.pheromoneView)
        self.viewsTabWidget.addTab(self.Pheromone, "")
        self.Result = QtWidgets.QWidget()
        self.Result.setObjectName("Result")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Result)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.resultView = QtWidgets.QGraphicsView(self.Result)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultView.sizePolicy().hasHeightForWidth())
        self.resultView.setSizePolicy(sizePolicy)
        self.resultView.setObjectName("resultView")
        self.horizontalLayout_5.addWidget(self.resultView)
        self.viewsTabWidget.addTab(self.Result, "")
        self.Schedule = QtWidgets.QWidget()
        self.Schedule.setObjectName("Schedule")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Schedule)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scheduleView = QtWidgets.QGraphicsView(self.Schedule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scheduleView.sizePolicy().hasHeightForWidth())
        self.scheduleView.setSizePolicy(sizePolicy)
        self.scheduleView.setObjectName("scheduleView")
        self.horizontalLayout_4.addWidget(self.scheduleView)
        self.viewsTabWidget.addTab(self.Schedule, "")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.History)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.historyView = QtWidgets.QGraphicsView(self.History)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyView.sizePolicy().hasHeightForWidth())
        self.historyView.setSizePolicy(sizePolicy)
        self.historyView.setObjectName("historyView")
        self.horizontalLayout_3.addWidget(self.historyView)
        self.viewsTabWidget.addTab(self.History, "")
        self.horizontalLayout.addWidget(self.viewsTabWidget)
        self.configScrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configScrollArea.sizePolicy().hasHeightForWidth())
        self.configScrollArea.setSizePolicy(sizePolicy)
        self.configScrollArea.setMinimumSize(QtCore.QSize(155, 0))
        self.configScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.configScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.configScrollArea.setWidgetResizable(True)
        self.configScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.configScrollArea.setObjectName("configScrollArea")
        self.configScrollAreaWidgetContents = QtWidgets.QWidget()
        self.configScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 132, 531))
        self.configScrollAreaWidgetContents.setObjectName("configScrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.configScrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.configGroupBox = QtWidgets.QGroupBox(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configGroupBox.sizePolicy().hasHeightForWidth())
        self.configGroupBox.setSizePolicy(sizePolicy)
        self.configGroupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.configGroupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.configGroupBox.setObjectName("configGroupBox")
        self.label = QtWidgets.QLabel(self.configGroupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.configGroupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 100, 20))
        self.label_2.setObjectName("label_2")
        self.algorithmComboBox = QtWidgets.QComboBox(self.configGroupBox)
        self.algorithmComboBox.setGeometry(QtCore.QRect(10, 40, 100, 22))
        self.algorithmComboBox.setObjectName("algorithmComboBox")
        self.algorithmComboBox.addItem("")
        self.algorithmComboBox.addItem("")
        self.renderComboBox = QtWidgets.QComboBox(self.configGroupBox)
        self.renderComboBox.setGeometry(QtCore.QRect(10, 90, 100, 22))
        self.renderComboBox.setObjectName("renderComboBox")
        self.renderComboBox.addItem("")
        self.renderComboBox.addItem("")
        self.verticalLayout_5.addWidget(self.configGroupBox)
        self.parametersGroupBox = QtWidgets.QGroupBox(self.configScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parametersGroupBox.sizePolicy().hasHeightForWidth())
        self.parametersGroupBox.setSizePolicy(sizePolicy)
        self.parametersGroupBox.setMinimumSize(QtCore.QSize(0, 270))
        self.parametersGroupBox.setMaximumSize(QtCore.QSize(16777215, 270))
        self.parametersGroupBox.setObjectName("parametersGroupBox")
        self.label_3 = QtWidgets.QLabel(self.parametersGroupBox)
        self.label_3.setGeometry(QtCore.QRect(15, 20, 100, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.parametersGroupBox)
        self.label_4.setGeometry(QtCore.QRect(15, 70, 100, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.parametersGroupBox)
        self.label_5.setGeometry(QtCore.QRect(15, 120, 100, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.parametersGroupBox)
        self.label_6.setGeometry(QtCore.QRect(15, 170, 100, 20))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.parametersGroupBox)
        self.label_8.setGeometry(QtCore.QRect(15, 220, 100, 12))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.parametersGroupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.parametersGroupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.parametersGroupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.parametersGroupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.parametersGroupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 240, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.parametersGroupBox)
        self.specificGroupBox = QtWidgets.QGroupBox(self.configScrollAreaWidgetContents)
        self.specificGroupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.specificGroupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.specificGroupBox.setObjectName("specificGroupBox")
        self.label_9 = QtWidgets.QLabel(self.specificGroupBox)
        self.label_9.setGeometry(QtCore.QRect(15, 20, 100, 20))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.specificGroupBox)
        self.label_7.setGeometry(QtCore.QRect(15, 70, 111, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.specificGroupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.specificGroupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_5.addWidget(self.specificGroupBox)
        self.configScrollArea.setWidget(self.configScrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.configScrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.consoleTabWidget.setCurrentIndex(1)
        self.viewsTabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AntScheduler"))
        self.RunButton.setText(_translate("MainWindow", "Start"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.consoleTabWidget.setTabText(self.consoleTabWidget.indexOf(self.logWidget), _translate("MainWindow", "Output log"))
        self.consoleTabWidget.setTabText(self.consoleTabWidget.indexOf(self.inputProcessWidget), _translate("MainWindow", "Process"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Process), _translate("MainWindow", "Process"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Pheromone), _translate("MainWindow", "Pheromone"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Result), _translate("MainWindow", "Result"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.Schedule), _translate("MainWindow", "Schedule"))
        self.viewsTabWidget.setTabText(self.viewsTabWidget.indexOf(self.History), _translate("MainWindow", "History"))
        self.configGroupBox.setTitle(_translate("MainWindow", "Configurations"))
        self.label.setText(_translate("MainWindow", "Algorithm type"))
        self.label_2.setText(_translate("MainWindow", "Render graph images"))
        self.algorithmComboBox.setItemText(0, _translate("MainWindow", "Ant System"))
        self.algorithmComboBox.setItemText(1, _translate("MainWindow", "Max-Min"))
        self.renderComboBox.setItemText(0, _translate("MainWindow", "Yes"))
        self.renderComboBox.setItemText(1, _translate("MainWindow", "No"))
        self.parametersGroupBox.setTitle(_translate("MainWindow", "Parameters"))
        self.label_3.setText(_translate("MainWindow", "Iterations"))
        self.label_4.setText(_translate("MainWindow", "Ant population"))
        self.label_5.setText(_translate("MainWindow", "Evaporation rate"))
        self.label_6.setText(_translate("MainWindow", "Pheromone potency"))
        self.label_8.setText(_translate("MainWindow", "init pheromone value"))
        self.specificGroupBox.setTitle(_translate("MainWindow", "Algorithm-specific"))
        self.label_9.setText(_translate("MainWindow", "Ants promoted "))
        self.label_7.setText(_translate("MainWindow", "Pheromone distribution"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

